### ISSUE TITLE
example problem

### ISSUE THREAD

**Issue by Gamewalker** [Saeven/zf3-circlical-autowire#2]
Hey, 
I am testing your modul and I got stuck, is it possible to produce the same code with annotation like I have here:

https://gist.github.com/Gamewalker/4219888d0874510e1040a59bf46d974a

Everything I tried ended in detail not found (view code: <?= $this->url('blog/detail', ['id' => $post->getId()]) ?>)

**Comment by Saeven** [comment]
Hi @Gamewalker 

Modified README and added that functionality!
Took about 5 minutes; related test is here:
https://github.com/Saeven/zf3-circlical-autowire/blob/master/bundle/Spec/CirclicalAutoWire/Service/RouterServiceSpec.php#L64

**Comment by Gamewalker** [comment]
Hey,
looks really nice, I will test it later. 
thanks

**Comment by Gamewalker** [comment]
hey,

could be me but I think the case if the parent controller is in another controller defined, isnt working. 
Like in the gist I provided.

Fatal error: Uncaught Exception: An autowired route route-0 declares a parent of blog, but blog was not defined. in /var/www/vendor/saeven/zf3-circlical-autowire/src/CirclicalAutoWire/Service/RouterService.php on line 63

**Comment by Saeven** [comment]
There was indeed no provision for parent routes across controllers.  I'll be able to add a quick something for that tonight.

**Comment by Saeven** [comment]
Tweaked to support cross-controller routing.  Test here:
https://github.com/Saeven/zf3-circlical-autowire/blob/master/bundle/Spec/CirclicalAutoWire/Service/RouterServiceSpec.php#L111

Let me know how things go!

**Comment by Saeven** [comment]
@Gamewalker Issue was all good?

**Comment by Gamewalker** [comment]
Hey,
couldnt test the cross controller thingy but the moment I updated to head, I couldnt run my website anymore. With the newest commit, the navigation cant find my named routes anymore. But there is no error message that could help, only route "add" not found and its defined like this:

``` php
/**
     * @Route("/add", parent="capacity", name="add")
     */
    public function addAction()
    {
         ...
    }
```

**Comment by Saeven** [comment]
Is your code on Git?

**Comment by Saeven** [comment]
One quick way to check, is to delete the generated `autowire.routes.php` file, and refresh to see if it regenerates.

**Comment by Gamewalker** [comment]
didnt work, it creates a new file but same error.

Uploaded my stuff to a private git and invited you, there is a branch with the newest commit, master is the one before.

**Comment by Saeven** [comment]
Checking your repo, you have a specific hash in your composer.json, that's the only problem.  It pinned a dev-master version along the way.

Just change from

```
"saeven/zf3-circlical-autowire": "dev-master#fcfcfc39084f4cb03f6ddbf7dc1fc53cce830d7f",
```

to

```
"saeven/zf3-circlical-autowire": "dev-master",
```

And composer update from there.  I've confirmed your routes will be ok.

**Comment by Saeven** [comment]
![screen shot 2016-10-28 at 10 05 49 pm](https://cloud.githubusercontent.com/assets/887224/19826519/bedaa8ec-9d5a-11e6-86e0-be19278425a5.png)

**Comment by Gamewalker** [comment]
No, my app isnt working with master, thats why I implemented the specific commit as fallback and created a branch for you with the master version where the error occurs.

**Comment by Gamewalker** [comment]
I deleted my vendor folder and autowtire file and downloaded everything again and I get the same error, I pushed this version to master. 

![unbenannt](https://cloud.githubusercontent.com/assets/241821/19830651/8a947584-9dfc-11e6-9ed5-ef83837640b8.PNG)

If I use the 

```
"saeven/zf3-circlical-autowire": "dev-master#fcfcfc39084f4cb03f6ddbf7dc1fc53cce830d7f",
```

its working fine

**Comment by Saeven** [comment]
If you can reinvite me (sorry) I'll push the small tweaks that make Things work. 

Scribbled on my iPhone

**Comment by Gamewalker** [comment]
Got it working for the navigation but if I run a command on CLI, I receive it again:

``` php
Fatal error: Uncaught Zend\Router\Exception\RuntimeException: Route with name "home" not found in C:\_DEV\www-zend\vendor\zendframework\zend-router\src\Http\TreeRouteStack.php on line 354

Zend\Router\Exception\RuntimeException: Route with name "home" not found in C:\_DEV\www-zend\vendor\zendframework\zend-router\src\Http\TreeRouteStack.php on line 354

Call Stack:
    0.0002     357272   1. {main}() C:\_DEV\www-zend\public\index.php:0
    0.0942    4878096   2. Zend\Mvc\Application->run() C:\_DEV\www-zend\public\index.php:50
    0.0945    4880592   3. Zend\Mvc\Application->completeRequest() C:\_DEV\www-zend\vendor\zendframework\zend-mvc\src\Application.php:326
    0.0945    4880592   4. Zend\EventManager\EventManager->triggerEvent() C:\_DEV\www-zend\vendor\zendframework\zend-mvc\src\Application.php:367
    0.0945    4880592   5. Zend\EventManager\EventManager->triggerListeners() C:\_DEV\www-zend\vendor\zendframework\zend-eventmanager\src\EventManager.php:143
    0.0945    4881168   6. Zend\Mvc\View\Http\DefaultRenderingStrategy->render() C:\_DEV\www-zend\vendor\zendframework\zend-eventmanager\src\EventManager.php:271
    0.1115    5804624   7. Zend\EventManager\EventManager->triggerEvent() C:\_DEV\www-zend\vendor\zendframework\zend-mvc\src\View\Http\DefaultRenderingStrategy.php:123
    0.1115    5804624   8. Zend\EventManager\EventManager->triggerListeners() C:\_DEV\www-zend\vendor\zendframework\zend-eventmanager\src\EventManager.php:143
    0.1116    5806088   9. Zend\Mvc\View\Http\DefaultRenderingStrategy->render() C:\_DEV\www-zend\vendor\zendframework\zend-eventmanager\src\EventManager.php:271
```

**Comment by Saeven** [comment]
Hey man, sorry I went AWOL a few days.  Been real busy with work-work.  The module was indeed disabled for CLI, I can lift the restriction.

I think you might indeed have singled something out with the parent/child relationship.  I'll write tests to attempt to break, and then fix the problem.

**Comment by Gamewalker** [comment]
A simple php public/index.php is throwing the exception, dunno why its calling the routing stuff if its disabled for console ^^

**Comment by Saeven** [comment]
I'll make the console work like in prod mode, relying on routes already discovered.

**Comment by Saeven** [comment]
Ok pushed that to dev-master.  WRT the child/parent issue, how did you get around your original report?

**Comment by Saeven** [comment]
@Gamewalker I'm on Gitter btw if it makes things easier

**Comment by Saeven** [comment]
Modified with this test:
https://github.com/Saeven/zf3-circlical-autowire/blob/master/bundle/Spec/CirclicalAutoWire/Service/RouterServiceSpec.php#L169

It's a condition that used to fail, now passes.  Let me know if you find any breaks.  This package is pretty nascent; thank you for your help.

**Comment by Gamewalker** [comment]
Its seems like its working now. Dunno why but if I call php index.php I get the html code displayed and not console style output, do you know what this could be?

**Comment by Saeven** [comment]
You've enabled Zend Console as a module, and have configured the CLI routes separately?  The auto wire is limited to http routes.

**Comment by Gamewalker** [comment]
Yeah and I created the config/controller like u did in the user module. It should be working in dev environment or not?

I just had time to test the multi controller thingy and its almost working, u forgot to add name somewhere:

``` php
'blog' => array(
        'type' => 'Zend\\Router\\Http\\Literal',
        'options' => array(
            'route' => '/blog',
            'defaults' => array(
                'controller' => 'Blog\\Controller\\ListController',
                'action' => 'index',
            ),
        ),
        'may_terminate' => true,
        'child_routes' => array(
            'detail' => array(
                'type' => 'Zend\\Router\\Http\\Segment',
                'options' => array(
                    'route' => '/:id',
                    'defaults' => array(
                        'action' => 'detail',
                    ),
                    'constraints' => array(
                        'id' => '\\d+',
                    ),
                ),
            ),
_______________________________________________________________________________
            'route-0' => array(
_______________________________________________________________________________
                'type' => 'Zend\\Router\\Http\\Literal',
                'options' => array(
                    'route' => '/add',
                    'defaults' => array(
                        'action' => 'add',
                        'controller' => 'Controller\\WriteController',
                    ),
                ),
            ),
        ),
    ),
```

created with:

``` php
/**
     * @Route("/add", defaults={"action":"add", "controller": Controller\WriteController::class}, parent="blog")
     **/
```

**Comment by Saeven** [comment]
```
/**
  * @Route("/add", name="somename", defaults={"action":"add", "controller": Controller\WriteController::class}, parent="blog")
  **/
```

Adding `name="somename"` should give it whatever name you need :)

**Comment by Gamewalker** [comment]
Ah fuck this, I go kill myself XD
All working fine now. Thanks
