### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Slamdunk** [Saeven/zf3-circlical-autowire#4]
Hi, this project seems interesting, but the lack of tests prevents its adoption at a business level.

Would love to see the code tested.

**Comment by Saeven** [comment]
Hi! There are quite a few tests written already; the bread and butter functionality is all documented here:
https://github.com/Saeven/zf3-circlical-autowire/tree/master/bundle/Spec

Coverage could admittedly be increased.

**Comment by Slamdunk** [comment]
Hi, I admit I was misled by the `bundle` folder name and the fact I'm not used with PHPSpec. Beside that, I was (too much) synthetic and I'm sorry.

For a business to rely on a third party library, a strong proof of validity is mandatory. As of yet this project looks very useful, but a 25% code-coverage is too few.

This is sad because your work was great and would be a pity to be pushed in the oblivion by the lack of adoption.

**Comment by Saeven** [comment]
No need to apologize, and I understand!  I mostly did this to satisfy my own laziness, and also for my team at work.  The common gripe was the 1:1 Factory to Controller need, which leads to a ton of boilerplate.  This package eliminates it completely.

The routing aspect was just extra laziness, and can be turned off.  There's a strong adversity to annotations in some camps as well.

I'll ping a release if I manage to increase coverage.

**Comment by Saeven** [comment]
Coverage raised to 91%.
