### ISSUE TITLE
Migrate to Laminas

### ISSUE THREAD

**Issue by matheusdelima** [Saeven/zf3-circlical-autowire#8]
Hi!

My team is working to migrate to Laminas.
But your module is not compatible with the new namespaces.

You have any plan to compatibilize your module?

`

( ! ) Fatal error: Uncaught Laminas\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "Zend\ModuleManager\ModuleManager" to a factory; are you certain you provided it during configuration? in /mnt/c/Projetos/sistema/vendor/laminas/laminas-servicemanager/src/ServiceManager.php on line 688
--

1 | 0.0002 | 394816 | {main}( ) | .../index.php:0
2 | 0.0173 | 609368 | Laminas\Mvc\Application::init( ) | .../index.php:47
3 | 0.1748 | 1751656 | Laminas\Mvc\Application->bootstrap( ) | .../Application.php:272
4 | 0.1887 | 1949896 | Laminas\EventManager\EventManager->triggerEvent( ) | .../Application.php:160
5 | 0.1887 | 1949896 | Laminas\EventManager\EventManager->triggerListeners( ) | .../EventManager.php:170
6 | 0.2041 | 2091032 | CirclicalAutoWire\Module->onBootstrap( ) | .../EventManager.php:321
7 | 0.9145 | 59590960 | Laminas\ServiceManager\ServiceManager->get( ) | .../Module.php:93
8 | 0.9145 | 59590960 | Laminas\ServiceManager\ServiceManager->doCreate( ) | .../ServiceManager.php:201

`

**Comment by Saeven** [comment]
Hi!  I do indeed plan to adopt Laminas!  Was just waiting for the dust to settle on their side.

**Comment by Saeven** [comment]
https://github.com/Saeven/zf3-circlical-autowire/pull/9

**Comment by Saeven** [comment]
Have tagged a release on 2.0 (pre) with Laminas support.  Let me know how things go!
https://github.com/Saeven/zf3-circlical-autowire/releases/tag/2.0

**Comment by Saeven** [comment]
@matheusdelima you had a chance to give it a go?

**Comment by matheusdelima** [comment]
Hi @Saeven,

Before requesting support, try to perform a login and failed. However, note that you can perform a new performance and believe that it is working well on my project.

**Comment by Saeven** [comment]
Hi Matheus.

What do you mean by "perform a new performance"?

Cheers!
Alex

**Comment by matheusdelima** [comment]
Hello Sorry my english.

In short, his new branch upgrading to laminas worked very well.

**Comment by Saeven** [comment]
Excellent!!  Thanks for confirming! ;)
